name: Build and Release Stream Deck Plugin

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          tag="${GITHUB_REF_NAME#v}"        # e.g. 1.2.3
          build="1"
          full="$tag.$build"                # 1.2.3.1
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "build=$build" >> $GITHUB_OUTPUT
          echo "full=$full" >> $GITHUB_OUTPUT

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.6.4

      - name: Install dependencies
        run: dart pub get

      - name: Compile Dart code
        run: dart compile exe bin/sc_mapper_dart.dart -o icu.veelume.sc-mapper.sdPlugin/plugin.exe

      - name: Set up Node.js
        uses: actions/setup-node@v4.2
        with:
          node-version: '20'

      - name: Install Stream Deck CLI
        run: npm install -g @elgato/cli@latest

      - name: Pack .streamDeckPlugin
        run: streamdeck pack icu.veelume.sc-mapper.sdPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamDeckPlugin
          path: icu.veelume.sc-mapper.streamDeckPlugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: icu.veelume.sc-mapper.streamDeckPlugin
